### ISSUE TITLE
[BUG] Вылетает как угодно

### ISSUE THREAD

**Issue by Igram4ik** [Elytrium/LimboAuth-SocialAddon#3]
Вылетает как угодно, пробовал всё, и менял джаву даже.

```
> [02:20:20 ERROR]: Exception in thread "main" com.google.common.util.concurrent.E                                                                                                 xecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoCla                                                                                                 ssDefFoundError: net/elytrium/limboauth/event/AuthPluginReloadEvent
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalC                                                                                                 ache.java:2049)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache.get(LocalCache.jav                                                                                                 a:3951)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache.getOrLoad(LocalCac                                                                                                 he.java:3974)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.                                                                                                 get(LocalCache.java:4935)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.                                                                                                 getUnchecked(LocalCache.java:4941)
> [02:20:20 ERROR]:       at com.google.inject.internal.FailableCache.get(Failable                                                                                                 Cache.java:54)
> [02:20:20 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.g                                                                                                 et(ConstructorInjectorStore.java:49)
> [02:20:20 ERROR]:       at com.google.inject.internal.ConstructorBindingImpl.ini                                                                                                 tialize(ConstructorBindingImpl.java:148)
> [02:20:20 ERROR]:       at com.google.inject.internal.InjectorImpl.initializeBin                                                                                                 ding(InjectorImpl.java:592)
> [02:20:20 ERROR]:       at com.google.inject.internal.AbstractBindingProcessor$P                                                                                                 rocessor.initializeBinding(AbstractBindingProcessor.java:176)
> [02:20:20 ERROR]:       at com.google.inject.internal.AbstractBindingProcessor$P                                                                                                 rocessor.lambda$scheduleInitialization$0(AbstractBindingProcessor.java:163)
> [02:20:20 ERROR]:       at com.google.inject.internal.ProcessedBindingData.initi                                                                                                 alizeBindings(ProcessedBindingData.java:49)
> [02:20:20 ERROR]:       at com.google.inject.internal.InternalInjectorCreator.in                                                                                                 itializeStatically(InternalInjectorCreator.java:126)
> [02:20:20 ERROR]:       at com.google.inject.internal.InternalInjectorCreator.bu                                                                                                 ild(InternalInjectorCreator.java:110)
> [02:20:20 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:87)
> [02:20:20 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:69)
> [02:20:20 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:59)
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.plugin.loader.java.JavaPlug                                                                                                 inLoader.createPlugin(JavaPluginLoader.java:119)
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.plugin.VelocityPluginManage                                                                                                 r.loadPlugins(VelocityPluginManager.java:151)
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.VelocityServer.loadPlugins(                                                                                                 VelocityServer.java:324)
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.VelocityServer.start(Veloci                                                                                                 tyServer.java:222)
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.Velocity.main(Velocity.java                                                                                                 :64)
> [02:20:20 ERROR]: Caused by: com.google.common.util.concurrent.ExecutionError: j                                                                                                 ava.lang.NoClassDefFoundError: net/elytrium/limboauth/event/AuthPluginReloadEven                                                                                                 t
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalC                                                                                                 ache.java:2049)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache.get(LocalCache.jav                                                                                                 a:3951)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache.getOrLoad(LocalCac                                                                                                 he.java:3974)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.                                                                                                 get(LocalCache.java:4935)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.                                                                                                 getUnchecked(LocalCache.java:4941)
> [02:20:20 ERROR]:       at com.google.inject.internal.FailableCache.get(Failable                                                                                                 Cache.java:54)
> [02:20:20 ERROR]:       at com.google.inject.internal.MembersInjectorStore.get(M                                                                                                 embersInjectorStore.java:69)
> [02:20:20 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.c                                                                                                 reateConstructor(ConstructorInjectorStore.java:75)
> [02:20:20 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.a                                                                                                 ccess$000(ConstructorInjectorStore.java:30)
> [02:20:20 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore$1                                                                                                 .create(ConstructorInjectorStore.java:38)
> [02:20:20 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore$1                                                                                                 .create(ConstructorInjectorStore.java:34)
> [02:20:20 ERROR]:       at com.google.inject.internal.FailableCache$1.load(Faila                                                                                                 bleCache.java:43)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$LoadingValueRefere                                                                                                 nce.loadFuture(LocalCache.java:3529)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.loadSync(L                                                                                                 ocalCache.java:2278)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.lockedGetO                                                                                                 rLoad(LocalCache.java:2155)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalC                                                                                                 ache.java:2045)
> [02:20:20 ERROR]:       ... 21 more
> [02:20:20 ERROR]: Caused by: java.lang.NoClassDefFoundError: net/elytrium/limboa                                                                                                 uth/event/AuthPluginReloadEvent
> [02:20:20 ERROR]:       at java.base/java.lang.Class.getDeclaredMethods0(Native                                                                                                  Method)
> [02:20:20 ERROR]:       at java.base/java.lang.Class.privateGetDeclaredMethods(C                                                                                                 lass.java:3334)
> [02:20:20 ERROR]:       at java.base/java.lang.Class.getDeclaredMethods(Class.ja                                                                                                 va:2446)
> [02:20:20 ERROR]:       at com.google.inject.internal.DeclaredMembers.getDeclare                                                                                                 dMethods(DeclaredMembers.java:48)
> [02:20:20 ERROR]:       at com.google.inject.spi.InjectionPoint.getDeclaredMetho                                                                                                 ds(InjectionPoint.java:804)
> [02:20:20 ERROR]:       at com.google.inject.spi.InjectionPoint.getInjectionPoin                                                                                                 ts(InjectionPoint.java:723)
> [02:20:20 ERROR]:       at com.google.inject.spi.InjectionPoint.forInstanceMetho                                                                                                 dsAndFields(InjectionPoint.java:423)
> [02:20:20 ERROR]:       at com.google.inject.internal.MembersInjectorStore.creat                                                                                                 eWithListeners(MembersInjectorStore.java:92)
> [02:20:20 ERROR]:       at com.google.inject.internal.MembersInjectorStore.acces                                                                                                 s$000(MembersInjectorStore.java:40)
> [02:20:20 ERROR]:       at com.google.inject.internal.MembersInjectorStore$1.cre                                                                                                 ate(MembersInjectorStore.java:49)
> [02:20:20 ERROR]:       at com.google.inject.internal.MembersInjectorStore$1.cre                                                                                                 ate(MembersInjectorStore.java:45)
> [02:20:20 ERROR]:       at com.google.inject.internal.FailableCache$1.load(Faila                                                                                                 bleCache.java:43)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$LoadingValueRefere                                                                                                 nce.loadFuture(LocalCache.java:3529)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.loadSync(L                                                                                                 ocalCache.java:2278)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.lockedGetO                                                                                                 rLoad(LocalCache.java:2155)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalC                                                                                                 ache.java:2045)
> [02:20:20 ERROR]:       ... 36 more
> [02:20:20 ERROR]: Caused by: java.lang.ClassNotFoundException: net.elytrium.limb                                                                                                 oauth.event.AuthPluginReloadEvent
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.lo                                                                                                 adClass0(PluginClassLoader.java:83)
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.lo                                                                                                 adClass(PluginClassLoader.java:60)
> [02:20:20 ERROR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader                                                                                                 .java:519)
> [02:20:20 ERROR]:       ... 52 more
> [02:20:20 ERROR]:       at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:126)
> [02:20:20 ERROR]:       at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
> [02:20:20 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:87)
> [02:20:20 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:69)
> [02:20:20 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:59)
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:119)
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:151)
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:324)
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:222)
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.Velocity.main(Velocity.java:64)
> [02:20:20 ERROR]: Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: net/elytrium/limboauth/event/AuthPluginReloadEvent
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4941)
> [02:20:20 ERROR]:       at com.google.inject.internal.FailableCache.get(FailableCache.java:54)
> [02:20:20 ERROR]:       at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:69)
> [02:20:20 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:75)
> [02:20:20 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30)
> [02:20:20 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38)
> [02:20:20 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:34)
> [02:20:20 ERROR]:       at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
> [02:20:20 ERROR]:       ... 21 more
> [02:20:20 ERROR]: Caused by: java.lang.NoClassDefFoundError: net/elytrium/limboauth/event/AuthPluginReloadEvent
> [02:20:20 ERROR]:       at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
> [02:20:20 ERROR]:       at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3334)
> [02:20:20 ERROR]:       at java.base/java.lang.Class.getDeclaredMethods(Class.java:2446)
> [02:20:20 ERROR]:       at com.google.inject.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:48)
> [02:20:20 ERROR]:       at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:804)
> [02:20:20 ERROR]:       at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:723)
> [02:20:20 ERROR]:       at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:423)
> [02:20:20 ERROR]:       at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:92)
> [02:20:20 ERROR]:       at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:40)
> [02:20:20 ERROR]:       at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:49)
> [02:20:20 ERROR]:       at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45)
> [02:20:20 ERROR]:       at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
> [02:20:20 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
> [02:20:20 ERROR]:       ... 36 more
> [02:20:20 ERROR]: Caused by: java.lang.ClassNotFoundException: net.elytrium.limboauth.event.AuthPluginReloadEvent
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:83)
> [02:20:20 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:60)
> [02:20:20 ERROR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
> [02:20:20 ERROR]:       ... 52 more
```
Использую jdk 16, velocity 3.1.1

**Comment by Igram4ik** [comment]
Простите тупой

**Comment by mdxd44** [comment]
ладно
