### ISSUE TITLE
[BUG] Couldn't pass ProxyInitializeEvent to limboauth-social-addon

### ISSUE THREAD

**Issue by 8Riven8** [Elytrium/LimboAuth-SocialAddon#31]
When I start the server -> console tell me:
[06:52:10 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth-social-addon
java.lang.IllegalArgumentException: connectionSource argument cannot be null
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.dao.DaoManager.createDao(DaoManager.java:44) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.table.TableUtils.createTableIfNotExists(TableUtils.java:73) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon.onReload(Addon.java:564) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon.onProxyInitialization(Addon.java:148) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Lmbda$4.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-93b6376b-b246)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.2.0-SNAPSHOT (git-93b6376b-b246)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.2.0-SNAPSHOT (git-93b6376b-b246)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

Screen:
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/104576430/229048191-630b58b6-d23c-4d53-a385-2b484efeb6c7.png">

**Comment by hevav** [comment]
Follow the issue template.
