### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ghost** [Elytrium/LimboAuth-SocialAddon#34]
я хочу использовать балансировку нагрузки velocity, но limboauth socialaddon дает ошибки на двух velocity

[15:27:30 ERROR] [net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.updatesreceivers.DefaultBotSession]: Error executing net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.meta.api.methods.updates.GetUpdates query: [409] Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error executing net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.meta.api.methods.updates.GetUpdates query: [409] Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
        at net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.meta.api.methods.PartialBotApiMethod.deserializeResponseInternal(PartialBotApiMethod.java:53) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.meta.api.methods.PartialBotApiMethod.deserializeResponseArray(PartialBotApiMethod.java:38) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.meta.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:83) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.getUpdatesFromServer(DefaultBotSession.java:260) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:189) ~[?:?]
[15:27:35 ERROR] [net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.updatesreceivers.DefaultBotSession]: Error executing net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.meta.api.methods.updates.GetUpdates query: [409] Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error executing net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.meta.api.methods.updates.GetUpdates query: [409] Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
        at net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.meta.api.methods.PartialBotApiMethod.deserializeResponseInternal(PartialBotApiMethod.java:53) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.meta.api.methods.PartialBotApiMethod.deserializeResponseArray(PartialBotApiMethod.java:38) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.meta.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:83) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.getUpdatesFromServer(DefaultBotSession.java:260) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:189) ~[?:?]

**Comment by hevav** [comment]
проблема кроется в том, что для балансировки сам бот должен быть не в плагине, а отдельно от велосити в целом. чуть позже реализую
