### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Crazinekit** [Elytrium/LimboAuth-SocialAddon#38]
Создал токен в вк группе, выдал ему все права, но даёт такую ошибку:
[19:43:49 ERROR] [net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest]: API error
net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.exceptions.ApiMessagesChatBotFeatureException: This is a chat bot feature, change this status in settings (912): This is a chat bot feature, change this status in settings
        at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.exceptions.ExceptionMapper.parseException(ExceptionMapper.java:338) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest.executeWithoutRetry(ApiRequest.java:104) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:79) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.VKSocial.sendMessage(VKSocial.java:192) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.AbstractSocial.sendMessage(AbstractSocial.java:55) ~[?:?]
        at net.elytrium.limboauth.socialaddon.SocialManager.lambda$broadcastMessage$15(SocialManager.java:171) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at net.elytrium.limboauth.socialaddon.SocialManager.broadcastMessage(SocialManager.java:171) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon.lambda$load$0(Addon.java:291) ~[?:?]
        at net.elytrium.limboauth.socialaddon.SocialManager.lambda$onMessageReceived$0(SocialManager.java:58) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at net.elytrium.limboauth.socialaddon.SocialManager.onMessageReceived(SocialManager.java:56) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.AbstractSocial.proceedMessage(AbstractSocial.java:35) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.VKSocial.onMessageNew(VKSocial.java:215) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.VKSocial.lambda$start$0(VKSocial.java:107) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.VKSocial.lambda$start$1(VKSocial.java:99) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Jaypasha** [comment]
> Создал токен в вк группе, выдал ему все права, но даёт такую ошибку: [19:43:49 ERROR] [net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest]: API error net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.exceptions.ApiMessagesChatBotFeatureException: This is a chat bot feature, change this status in settings (912): This is a chat bot feature, change this status in settings at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.exceptions.ExceptionMapper.parseException(ExceptionMapper.java:338) ~[?:?] at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest.executeWithoutRetry(ApiRequest.java:104) ~[?:?] at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:79) ~[?:?] at net.elytrium.limboauth.socialaddon.social.VKSocial.sendMessage(VKSocial.java:192) ~[?:?] at net.elytrium.limboauth.socialaddon.social.AbstractSocial.sendMessage(AbstractSocial.java:55) ~[?:?] at net.elytrium.limboauth.socialaddon.SocialManager.lambda$broadcastMessage$15(SocialManager.java:171) ~[?:?] at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?] at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239) ~[?:?] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?] at net.elytrium.limboauth.socialaddon.SocialManager.broadcastMessage(SocialManager.java:171) ~[?:?] at net.elytrium.limboauth.socialaddon.Addon.lambda$load$0(Addon.java:291) ~[?:?] at net.elytrium.limboauth.socialaddon.SocialManager.lambda$onMessageReceived$0(SocialManager.java:58) ~[?:?] at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] at net.elytrium.limboauth.socialaddon.SocialManager.onMessageReceived(SocialManager.java:56) ~[?:?] at net.elytrium.limboauth.socialaddon.social.AbstractSocial.proceedMessage(AbstractSocial.java:35) ~[?:?] at net.elytrium.limboauth.socialaddon.social.VKSocial.onMessageNew(VKSocial.java:215) ~[?:?] at net.elytrium.limboauth.socialaddon.social.VKSocial.lambda$start$0(VKSocial.java:107) ~[?:?] at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?] at net.elytrium.limboauth.socialaddon.social.VKSocial.lambda$start$1(VKSocial.java:99) ~[?:?] at java.lang.Thread.run(Thread.java:834) [?:?]

Впн включи
