### ISSUE TITLE
[BUG] VKAPI Error

### ISSUE THREAD

**Issue by kainlighty** [Elytrium/LimboAuth-SocialAddon#39]
When connecting some players (after updating the velocity to 266+), it began to give an error.
```
[00:23:49 ERROR] [net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest]: API error
net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.exceptions.ApiParamException: One of the parameters specified was missing or invalid (100): One of the parameters specified was missing or invalid: invalid event_id
        at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.exceptions.ExceptionMapper.parseException(ExceptionMapper.java:118) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest.executeWithoutRetry(ApiRequest.java:104) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:79) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.VKSocial.onMessageEvent(VKSocial.java:244) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.VKSocial.lambda$start$0(VKSocial.java:111) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.VKSocial.lambda$start$1(VKSocial.java:99) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[00:23:49 ERROR]: net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.exceptions.ApiParamException: One of the parameters specified was missing or invalid (100): One of the parameters specified was missing or invalid: invalid event_id
[00:23:49 ERROR]:       at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.exceptions.ExceptionMapper.parseException(ExceptionMapper.java:118)
[00:23:49 ERROR]:       at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest.executeWithoutRetry(ApiRequest.java:104)
[00:23:49 ERROR]:       at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:79)
[00:23:49 ERROR]:       at net.elytrium.limboauth.socialaddon.social.VKSocial.onMessageEvent(VKSocial.java:244)
[00:23:49 ERROR]:       at net.elytrium.limboauth.socialaddon.social.VKSocial.lambda$start$0(VKSocial.java:111)
[00:23:49 ERROR]:       at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[00:23:49 ERROR]:       at net.elytrium.limboauth.socialaddon.social.VKSocial.lambda$start$1(VKSocial.java:99)
[00:23:49 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

All plugins on velocity are of the latest versions, as is the velocity build itself.

**Comment by kainlighty** [comment]
Провёл небольшие тесты, оказалось что виноват пункт "Long Poll API" -> "Типы событий" -> "Прочитанность сообщений".

Имею возможность выключать прочтение сообщений и понял, что если выводится event "message_read"
```
[02:48:35] [Thread-3/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: message_read
[02:48:35] [Thread-3/INFO] [com.velocitypowered.proxy.console.VelocityConsole]: {"from_id":276672300,"peer_id":-170725242,"read_message_id":5913,"conversation_message_id":263}
```

Порядок ивентов при ошибке: "message_event", после "message_reply", после "message_read".
Выключаю галочку прочитанность сообщений и естественно при дебаге "message_read" не воспроизводится и ошибки нет.

Хоть я рекодил плагин под себя, мне не дает понятия почему так происходит. Как в этом плагине sdk, так и в другом sdk прочитанность сообщений лает в консоль. Пока не решил проблему, с вк очень не дружу, tg one love
