### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by botinok224** [Elytrium/LimboAuth-SocialAddon#41]
При активированной Discord привязке выдаёт ошибку на запуске

[13:27:03 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth-social-addon
java.lang.NoSuchMethodError: org.apache.logging.slf4j.Log4jLoggerFactory: method 'void <init>()' not found
        at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:53) ~[?:?]
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:41) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.net.dv8tion.jda.internal.utils.JDALogger.<clinit>(JDALogger.java:49) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.net.dv8tion.jda.internal.entities.EntityBuilder.<clinit>(EntityBuilder.java:78) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.net.dv8tion.jda.api.entities.Activity.playing(Activity.java:129) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.net.dv8tion.jda.api.entities.Activity.of(Activity.java:282) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.DiscordSocial.start(DiscordSocial.java:65) ~[?:?]
        at net.elytrium.limboauth.socialaddon.SocialManager.start(SocialManager.java:97) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon.load(Addon.java:177) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon.onReload(Addon.java:560) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon.onProxyInitialization(Addon.java:148) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Lmbda$12.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-294.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-294.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-294.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
        
       
  
Далее плагин просто не работает как нужно (не запрашивает 2FA нигде)
Данная ошибка воспроизводиться только с Discord (enabled: true). С  включенным телеграмом и ВК ошибку не выдаёт.
Данная ошибка воспроизводиться на последней версии плагина под последний velocity
LimboApi, LimboFilter, LimboAuth - на сервере все последней версии под последний velocty (#294)
Ядро Velocity - #294

**Comment by kainlighty** [comment]
С телегой тоже трабл с кнопками (если отсылать inline и обычные). Я попытался пофиксить, но не разобрал его идею, хз, исправит, нет

**Comment by botinok224** [comment]
> удали папку org/slf4j внутри плагина

помогло, спасибо
