### ISSUE TITLE
[BUG] VK

### ISSUE THREAD

**Issue by Slaimhh1337** [Elytrium/LimboAuth-SocialAddon#48]
При привязке в вк выдает ошибку:

[net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest]: API error
net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.exceptions.ApiMessagesChatBotFeatureException: This is a chat bot feature, change this status in settings (912): This is a chat bot feature, change this status in settings
        at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.exceptions.ExceptionMapper.parseException(ExceptionMapper.java:338) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest.executeWithoutRetry(ApiRequest.java:104) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:79) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.VKSocial.sendMessage(VKSocial.java:205) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.VKSocial.sendMessage(VKSocial.java:216) ~[?:?]
        at net.elytrium.limboauth.socialaddon.SocialManager.lambda$broadcastMessage$9(SocialManager.java:147) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at net.elytrium.limboauth.socialaddon.SocialManager.broadcastMessage(SocialManager.java:147) ~[?:?]
        at net.elytrium.limboauth.socialaddon.SocialManager.broadcastMessage(SocialManager.java:140) ~[?:?]
        at net.elytrium.limboauth.socialaddon.listener.LimboAuthListener.lambda$new$1(LimboAuthListener.java:122) ~[?:?]
        at net.elytrium.limboauth.socialaddon.SocialManager.onButtonClicked(SocialManager.java:72) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.AbstractSocial.proceedButton(AbstractSocial.java:39) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.TelegramSocial$TGBot.onUpdateReceived(TelegramSocial.java:182) ~[?:?]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:317) ~[?:?]
[02:07:30 ERROR] [net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest]: API error
net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.exceptions.ApiMessagesChatBotFeatureException: This is a chat bot feature, change this status in settings (912): This is a chat bot feature, change this status in settings
        at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.exceptions.ExceptionMapper.parseException(ExceptionMapper.java:338) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest.executeWithoutRetry(ApiRequest.java:104) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:79) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.VKSocial.sendMessage(VKSocial.java:205) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.VKSocial.sendMessage(VKSocial.java:216) ~[?:?]
        at net.elytrium.limboauth.socialaddon.SocialManager.lambda$broadcastMessage$9(SocialManager.java:147) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at net.elytrium.limboauth.socialaddon.SocialManager.broadcastMessage(SocialManager.java:147) ~[?:?]
        at net.elytrium.limboauth.socialaddon.SocialManager.broadcastMessage(SocialManager.java:140) ~[?:?]
        at net.elytrium.limboauth.socialaddon.listener.LimboAuthListener.onGameProfile(LimboAuthListener.java:192) ~[?:?]
        at net.elytrium.limboauth.socialaddon.listener.Lmbda$20.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]

Пожалуйста помогите

**Comment by SkyWatcher2019** [comment]
> This is a chat bot feature, change this status in settings

Включите функции бота в настройках сообщества.
