### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by heper651** [Elytrium/LimboAuth-SocialAddon#49]
[12:15:42 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth-social-addon 1.0.10
java.lang.NoSuchMethodError: org.apache.logging.slf4j.Log4jLoggerFactory: method 'void <init>()' not found
        at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:53) ~[?:?]
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:41) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:421) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:412) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.net.dv8tion.jda.internal.utils.JDALogger.<clinit>(JDALogger.java:49) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.net.dv8tion.jda.internal.utils.IOUtil.<clinit>(IOUtil.java:35) ~[?:?]
        at net.elytrium.limboauth.socialaddon.thirdparty.net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1741) ~[?:?]
        at net.elytrium.limboauth.socialaddon.social.DiscordSocial.start(DiscordSocial.java:67) ~[?:?]
        at net.elytrium.limboauth.socialaddon.SocialManager.start(SocialManager.java:97) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon.load(Addon.java:177) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon.onReload(Addon.java:560) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon.onProxyInitialization(Addon.java:148) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Lmbda$6.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by UserNugget** [comment]
Looks like you should [update](https://github.com/Elytrium/LimboAuth-SocialAddon/releases/tag/1.0.11-snapshot-1) this plugin
